services:
  - type: web
    name: reachinbox-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://reachinbox-sigma-umber.vercel.app
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: ETHEREAL_HOST
        value: smtp.ethereal.email
      - key: ETHEREAL_PORT
        value: 587
      - key: ETHEREAL_USER
        sync: false
      - key: ETHEREAL_PASS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: WORKER_CONCURRENCY
        value: 5
      - key: MIN_DELAY_BETWEEN_EMAILS_MS
        value: 2000
      - key: MAX_EMAILS_PER_HOUR_PER_SENDER
        value: 200
